name: bokain_webshop
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
author: dmarl <dmarlovic83@gmail.com>
environment:
    sdk: '>=2.0.0-dev.65.0 <3.0.0'
dependencies:
  angular: ^5.0.0-beta+3
  angular_components: ^0.9.0-beta+3
  angular_forms: ^2.0.0-beta+3
  angular_router: ^2.0.0-alpha+18
  bokain_models:    
    path: ../bokain_models
  bokain_consultation:    
    path: ../bokain_consultation 
  grid:
    git: https://github.com/afpatmin/grid.git

  sass_builder: ^2.1.1  
  angular_analyzer_plugin: 0.0.17

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.1
