name: bokain_webshop
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
author: dmarl <dmarlovic83@gmail.com>
environment:
    sdk: '>=2.0.0-dev.44.0 <2.0.0'
dependencies:
  angular: ^5.0.0-alpha+10
  angular_components: ^0.9.0-alpha+9
  bokain_models:
    git: https://github.com/afpatmin/bokain_models.git
  grid:
    git: https://github.com/afpatmin/grid.git
  sass_builder: ^1.1.5
dev_dependencies:
  build_runner: ^0.8.2+2
  build_web_compilers: any
