name: bokain_webshop
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
author: dmarl <dmarlovic83@gmail.com>
environment:
    sdk: '>=2.0.0-dev.58.0 <2.0.0'
dependencies:
  angular: ^5.0.0-alpha+13
  angular_components: ^0.9.0-alpha+13
  angular_forms: ^2.0.0-alpha+5
  bokain_models:
    #git: https://github.com/afpatmin/bokain_models.git
    path: ../bokain_models
  sass: 1.3.2
  grid:
    git: https://github.com/afpatmin/grid.git

  sass_builder: ^2.0.0

dev_dependencies:
  build_runner: ^0.8.9
  build_web_compilers: ^0.4.0+1  
