name: bokain_webshop
description: A web app that uses AngularDart Components
version: 0.0.1
homepage: https://www.github.com/dejan-marlovic/bokain-webshop
author: afpatmin <patrick.minogue@gmail.com>
environment:
    sdk: '>=2.0.0 <3.0.0'
dependencies:
  angular: ^5.1.0
  angular_components: ^0.10.0
  angular_forms: ^2.1.0
  angular_router: ^2.0.0-alpha+20
  bokain_models:    
    path: ../bokain_models
  bokain_consultation:    
    path: ../bokain_consultation 
  grid:
    git: https://github.com/afpatmin/grid
  persistent_data: ^0.1.3
  sass_builder: ^2.1.2

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.4+2